var wpdiscuzEditorOptions = {
	modules: {
		toolbar: "",
		counter: {
			uniqueID: "",
			maxcount: 0,
			mincount: 1,
		},
	},
	placeholder: "Seja o Primeiro a Comentar!",
	theme: 'snow',
	debug: 'error'
};

var wpdiscuzAjaxObj = {
	"wc_hide_replies_text": "Esconder Respostas",
	"wc_show_replies_text": "View Replies",
	"wc_msg_required_fields": "Please fill out required fields",
	"wc_invalid_field": "A informa\u00e7\u00e3o de algum campo \u00e9 inv\u00e1lida",
	"wc_error_empty_text": "por favor, preencha este campo para comentar",
	"wc_error_url_text": "url is invalid",
	"wc_error_email_text": "Endere\u00e7o de e-mail inv\u00e1lido",
	"wc_invalid_captcha": "Captcha Inv\u00e1lida",
	"wc_login_to_vote": "Voc\u00ea deve estar autenticado para votar",
	"wc_deny_voting_from_same_ip": "Voc\u00ea n\u00e3o tem permiss\u00e3o para votar neste coment\u00e1rio",
	"wc_self_vote": "N\u00e3o pode votar no seu coment\u00e1rio",
	"wc_vote_only_one_time": "Voc\u00ea j\u00e1 votou para este coment\u00e1rio",
	"wc_voting_error": "Erro ao votar",
	"wc_comment_edit_not_possible": "Sorry, this comment is no longer possible to edit",
	"wc_comment_not_updated": "Lamentamos, mas o coment\u00e1rio n\u00e3o foi atualizado",
	"wc_comment_not_edited": "Voc\u00ea n\u00e3o fez altera\u00e7\u00f5es",
	"wc_msg_input_min_length": "Input is too short",
	"wc_msg_input_max_length": "Input is too long",
	"wc_spoiler_title": "Spoiler Title",
	"wc_cannot_rate_again": "You cannot rate again",
	"wc_not_allowed_to_rate": "You're not allowed to rate here",
	"wc_follow_user": "Follow this user",
	"wc_unfollow_user": "Unfollow this user",
	"wc_follow_success": "You started following this comment author",
	"wc_follow_canceled": "You stopped following this comment author.",
	"wc_follow_email_confirm": "Please check your email and confirm the user following request.",
	"wc_follow_email_confirm_fail": "Sorry, we couldn't send confirmation email.",
	"wc_follow_login_to_follow": "Please login to follow users.",
	"wc_follow_impossible": "We are sorry, but you can't follow this user.",
	"wc_follow_not_added": "Following failed. Please try again later.",
	"is_user_logged_in": "",
	"commentListLoadType": "0",
	"commentListUpdateType": "0",
	"commentListUpdateTimer": "30",
	"liveUpdateGuests": "0",
	"wordpressThreadCommentsDepth": "5",
	"wordpressIsPaginate": "0",
	"commentTextMaxLength": null,
	"commentTextMinLength": "1",
	"storeCommenterData": "100000",
	"socialLoginAgreementCheckbox": "1",
	"enableFbLogin": "0",
	"enableFbShare": "0",
	"facebookAppID": "",
	"facebookUseOAuth2": "0",
	"enableGoogleLogin": "0",
	"googleClientID": "",
	"googleClientSecret": "",
	"cookiehash": "a7e05504d9958fe66da971b36c0d910e",
	"isLoadOnlyParentComments": "0",
	"scrollToComment": "1",
	"commentFormView": "collapsed",
	"enableDropAnimation": "1",
	"isNativeAjaxEnabled": "1",
	"enableBubble": "0",
	"bubbleLiveUpdate": "0",
	"bubbleHintTimeout": "45",
	"bubbleHintHideTimeout": "10",
	"cookieHideBubbleHint": "wpdiscuz_hide_bubble_hint",
	"bubbleShowNewCommentMessage": "1",
	"bubbleLocation": "content_left",
	"firstLoadWithAjax": "0",
	"wc_copied_to_clipboard": "Copied to clipboard!",
	"inlineFeedbackAttractionType": "blink",
	"loadRichEditor": "1",
	"wpDiscuzReCaptchaSK": "",
	"wpDiscuzReCaptchaTheme": "light",
	"wpDiscuzReCaptchaVersion": "2.0",
	"wc_captcha_show_for_guest": "0",
	"wc_captcha_show_for_members": "0",
	"wpDiscuzIsShowOnSubscribeForm": "0",
	"wmuEnabled": "1",
	"wmuInput": "wmu_files",
	"wmuMaxFileCount": "1",
	"wmuMaxFileSize": "2097152",
	"wmuPostMaxSize": "1073741824",
	"wmuIsLightbox": "1",
	"wmuMimeTypes": {
		"jpg": "image\/jpeg",
		"jpeg": "image\/jpeg",
		"jpe": "image\/jpeg",
		"gif": "image\/gif",
		"png": "image\/png",
		"bmp": "image\/bmp",
		"tiff": "image\/tiff",
		"tif": "image\/tiff",
		"ico": "image\/x-icon"
	},
	"wmuPhraseConfirmDelete": "Are you sure you want to delete this attachment?",
	"wmuPhraseNotAllowedFile": "Not allowed file type",
	"wmuPhraseMaxFileCount": "Maximum number of uploaded files is 1",
	"wmuPhraseMaxFileSize": "Maximum upload file size is 2MB",
	"wmuPhrasePostMaxSize": "Maximum post size is 1024MB",
	"msgEmptyFile": "File is empty. Please upload something more substantial. This error could also be caused by uploads being disabled in your php.ini or by post_max_size being defined as smaller than upload_max_filesize in php.ini.",
	"msgPostIdNotExists": "Post ID not exists",
	"msgUploadingNotAllowed": "Sorry, uploading not allowed for this post",
	"msgPermissionDenied": "You do not have sufficient permissions to perform this action",
	"wmuSecurity": "30845e767f",
	"wmuKeyImages": "images",
	"wmuSingleImageWidth": "auto",
	"wmuSingleImageHeight": "200",
	"version": "7.1.3",
	"wc_post_id": "28",
	"loadLastCommentId": "0",
	"isCookiesEnabled": "1",
	"dataFilterCallbacks": [],
	"is_email_field_required": "1",
	"url": "https:\/\/zaganellioliveira.com.br\/wp-admin\/admin-ajax.php",
	"customAjaxUrl": "https:\/\/zaganellioliveira.com.br\/wp-content\/plugins\/wpdiscuz\/utils\/ajax\/wpdiscuz-ajax.php",
	"bubbleUpdateUrl": "https:\/\/zaganellioliveira.com.br\/wp-json\/wpdiscuz\/v1\/update",
	"restNonce": "e21c12290c"
};
var wpdiscuzUCObj = {
	"msgConfirmDeleteComment": "Are you sure you want to delete this comment?",
	"msgConfirmCancelSubscription": "Are you sure you want to cancel this subscription?",
	"msgConfirmCancelFollow": "Are you sure you want to cancel this follow?",
	"additionalTab": "0"
};